### ISSUE TITLE
"CodeWarrior for Embedded PowerPC binaries" download link is no longer available

### ISSUE THREAD

**Issue by SuperNReal** [NSMBW-Community/NSMBW-Decomp#29]
in [README.md](https://github.com/NSMBW-Community/NSMBW-Decomp/blob/master/README.md) right [here](https://github.com/NSMBW-Community/NSMBW-Decomp#setup) in the 5th step, the download link for "CodeWarrior for Embedded PowerPC binaries" redirects to a [page](https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip) that says "This content is no longer available." instead of giving me the files, pls fix,

thx for reading.

**Comment by CLF78** [comment]
Fixed. Thanks for reporting!
